run:
  concurrency: 4
  skip-dirs:
    - proto
output:
  format: colored-line-number
  sort-results: true
linters:
  disable-all: true
  enable:
    - unused
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - dupl
    - goimports
