version: '3'
networks:
  intranet:
    driver: bridge

services:
  proxy:
    container_name: "tech-tinker_proxy"
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/build/proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - intranet
    restart: unless-stopped
  api:
    container_name: "public_api"
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    networks:
      - intranet
    restart: unless-stopped
  auth:
    container_name: "auth_api"
    build:
      context: .
      dockerfile: ./build/auth/Dockerfile
    networks:
      - intranet
